version: "2.0"

services:
  base_blockchain_mqtt_broker:
    container_name: base_blockchain_mqtt_broker
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ../envs/mosquitto/pwfile:/mosquitto/config/pwfile
      - ../envs/mosquitto/aclfile:/mosquitto/config/aclfile
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - base_blockchain_network

networks:
  base_blockchain_network:
    driver: bridge
